"""added underlying_price column

Revision ID: ecc8f294a9ab
Revises: 
Create Date: 2025-06-19 16:21:34.802326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc8f294a9ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gex_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('net_gex', sa.Float(), nullable=False),
    sa.Column('abs_gex', sa.Float(), nullable=False),
    sa.Column('call_gex', sa.Float(), nullable=False),
    sa.Column('put_gex', sa.Float(), nullable=False),
    sa.Column('call_oi', sa.BigInteger(), nullable=True),
    sa.Column('put_oi', sa.BigInteger(), nullable=True),
    sa.Column('total_oi', sa.BigInteger(), nullable=True),
    sa.Column('underlying_price', sa.Float(), nullable=True),
    sa.Column('call_gamma', sa.Float(), nullable=True),
    sa.Column('put_gamma', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gex_instrument_timestamp', 'gex_analysis', ['instrument', 'timestamp'], unique=False)
    op.create_index('idx_gex_net_gex', 'gex_analysis', ['net_gex'], unique=False)
    op.create_index('idx_gex_strike_expiry', 'gex_analysis', ['strike', 'expiry'], unique=False)
    op.create_table('gex_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('total_net_gex', sa.Float(), nullable=False),
    sa.Column('gamma_flip_level', sa.Float(), nullable=True),
    sa.Column('max_positive_gex_strike', sa.Float(), nullable=True),
    sa.Column('max_positive_gex_value', sa.Float(), nullable=True),
    sa.Column('max_negative_gex_strike', sa.Float(), nullable=True),
    sa.Column('max_negative_gex_value', sa.Float(), nullable=True),
    sa.Column('max_abs_gex_strike', sa.Float(), nullable=True),
    sa.Column('max_abs_gex_value', sa.Float(), nullable=True),
    sa.Column('max_call_oi_strike', sa.Float(), nullable=True),
    sa.Column('max_call_oi_value', sa.BigInteger(), nullable=True),
    sa.Column('max_put_oi_strike', sa.Float(), nullable=True),
    sa.Column('max_put_oi_value', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_summary_instrument_timestamp', 'gex_summary', ['instrument', 'timestamp'], unique=False)
    op.add_column('optionchain_snapshots', sa.Column('underlying_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('optionchain_snapshots', 'underlying_price')
    op.drop_index('idx_summary_instrument_timestamp', table_name='gex_summary')
    op.drop_table('gex_summary')
    op.drop_index('idx_gex_strike_expiry', table_name='gex_analysis')
    op.drop_index('idx_gex_net_gex', table_name='gex_analysis')
    op.drop_index('idx_gex_instrument_timestamp', table_name='gex_analysis')
    op.drop_table('gex_analysis')
    # ### end Alembic commands ###
